export enum ERRORTYPES {
    UNKNOWN = 'UNKNOWN',
    UNKNOWN_FUNCTION = 'UNKNOWN_FUNCTION',
    JAVASCRIPT_ERROR = 'JAVASCRIPT_ERROR',
    BUSINESS_ERROR = 'BUSINESS_ERROR',
    LOG_ERROR = 'LOG_ERROR',
    FETCH_ERROR = 'HTTP_ERROR',
    VUE_ERROR = 'VUE_ERROR',
    RESOURCE_ERROR = 'RESOURCE_ERROR',
    PROMISE_ERROR = 'PROMISE_ERROR'
}