export enum ERRORTYPES {
    JAVASCRIPT_ERROR = 'JAVASCRIPT_ERROR',
    BUSINESS_ERROR = 'BUSINESS_ERROR',
    LOG_ERROR = 'LOG_ERROR',
    FETCH_ERROR = 'HTTP_ERROR',
    RESOURCE_ERROR = 'RESOURCE_ERROR',
    PROMISE_ERROR = 'PROMISE_ERROR'
}